baseURL: https://mdr.dev
languageCode: en-us
title: Mike DuRussel
theme: mdr
enableGitInfo: true

# Theme Parameters.
params:
  realName: Mike DuRussel
  bio: I'm an infrastructure and systems engineer with a passion for tinkering.
  whois: |
    Mike DuRussel is an infrastructure and systems engineer, currently working for
    <a href="https://www.squarespace.com" target="_new">Squarespace</a>. He created
    this site to share his thoughts and personal projects with those who are curious.
    <br><br>
    You can navigate the website using the hierarchy below.
  preScripts:
    - https://unpkg.com/typed.js@2.0.132/dist/typed.umd.js
    - /js/script.js
  scripts: []